#' Create a power curve for a specific Ti level using the zero turbulence method
#' 
#' \code{ZTTrainBaselinePCModel} creates a basic model of turbine power performance. The IEC method of binning to create.
#' 
#' The input to this function is generated by 
#' \code{\link{ZTTrainFinalTurbineModel}}.
#' 
#' @param PC.param a set of parameters describing the power curve
#' @param ws observations of wind speed
#' @param Ti observations of turbulence intensity
#' @param power observations of power
#' @param rho
#' @param NewTi the new value of turbulence intensity
#' @return site specific power curve
#' @export
#' 
#' @family zero-turbulence power curve methods
#'   

ZTTrainBaselinePCModel <- function(ws,
                                   power,
                                   ti,
                                   ws.cutin = 2){

PCBaseline <- PCTrainTurbineModel(ws = ws,
                                  power = power,
                                  ti = ti,
                                  ws.cutin = ws.cutin)
# remove data points above rated where power is 0
PCBaseline.ws.max <- PCBaseline$ws.binmean[which.max(PCBaseline$power.binmean)]
PCBaseline <- PCBaseline[(PCBaseline$ws.binmean <= PCBaseline.ws.max),]
# extrapolate out to 100 m/s

PCBaseline <- rbind(PCBaseline,
                    data.frame(ws.binmin = seq(ceiling(PCBaseline.ws.max/0.5)*0.5+0.25,
                                               50, 0.5),
                               ws.binmax = seq(ceiling(PCBaseline.ws.max/0.5)*0.5+0.75,
                                               50.25, 0.5),
                               ws.binnpoints = 3,
                               ws.binmean = seq(ceiling(PCBaseline.ws.max/0.5)*0.5+0.5,
                                                50,0.5),
                               ti.binmean = NA,                               
                               power.binmean = max(PCBaseline$power.binmean),
                               power.binsd = NA))
return(PCBaseline)
}